### ISSUE TITLE
package for 239-18.el8_1.2

### ISSUE THREAD

**Issue by bigHosting** [FelixSchwarz/epel8-networkd#2]
Hi Felix,

Is there any automated way for me to rebuild systemd-networkd every time there is a CentOS package update? Today I was trying to build a new VM and Ansible failed because 239-18.el8_1.2 of systemd-networkd package could not be found . I don't want to bug you every time there is a minor release ...

Thank you!

**Comment by FelixSchwarz** [comment]
Well, the problem is that pinned a very specific systemd version because this networkd is built against a shared library and I did not want to take any chances. I suspect the current version would work just fine even with an updated systemd.

There is an alternative approach by long-time Fedora contributor Robert Scheck: He assumes a stable DBUS interface between networkd and systemd. Then he packages the Fedora sources (= latest networkd version) and builds a static binary. The main advantage is that this static binary is not dependent on a specific systemd version so you don't have upgrade hassles (+ security support from Fedora, more networkd features).

Robert's package is not yet in EPEL but Neal recently mentioned that he will do the review: https://bugzilla.redhat.com/show_bug.cgi?id=1789146

I did not take that approach initially as I'm not sure how stable systemd's DBUS interface is. However I trust Robert's judgement there so if his package makes it into EPEL I'll probably make the switch as well.

**Comment by bigHosting** [comment]
Felix,

Thank you so much for the information, it makes more sense to build a statically compiled version and not go through the process every time RH releases a newer version.
 
I am still recompiling Robert's systemd-extras package, it failed on the first try with ninja errors, but it could be my hardening that interferes with rpmbuild. I will give it another go shortly

You are right, older systemd-networkd works fine with newer systemd!

**Comment by robert-scheck** [comment]
> I did not take that approach initially as I'm not sure how stable systemd's DBUS interface is. However I trust Robert's judgement there so if his package makes it into EPEL I'll probably make the switch as well.

Unfortunately, there is indeed some uncertainty…and only the time will tell.
